image:
  repository: etl-dynamic-workers-app
  tag: "a709cb0"
  pullPolicy: Always

instances:
  - name: etl-alpha
    dbType: mysql
    dbUser: alpha-user
    bktName: bkt-Alpha-mock
  - name: etl-bravo
    dbType: oracle
    dbUser: bravo-user
    bktName: bkt-Bravo-mock
  - name: etl-charlie
    dbType: postgres
    dbUser: charlie-user
    bktName: bkt-Foxtrot-mock
  - name: etl-delta
    dbType: postgres
    dbUser: delta-user
    bktName: bkt-Foxtrot-mock
    
