image:
  pullPolicy: Always

workers:
  etl-alpha:
    repository: "etl-core-app"
    tag: "latest"
    dbType: "mysql"   
  
  etl-bravo:
    repository: "etl-core-app"
    tag: "3408df9"
    dbType: "oracle" 
  
  etl-charlie:
    repository: "etl-core-app"
    tag: "3408df9"
    dbType: "postgres"
  
  etl-delta:
    repository: "etl-core-app"
    tag: "3408df9"
    dbType: "postgres"
