{{- range .Values.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
  labels:
    app: etl
    instance: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: {{ .name }}
  template:
    metadata:
      labels:
        instance: {{ .name }}
    spec:
      {{- if $.Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ $.Values.image.pullSecret }}
      {{- end }}
      containers:
      - name: etl-process
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy | default "Always" }}
        envFrom:
        - configMapRef:
            name: {{ $.Chart.Name }}-{{ .name }}-config
        volumeMounts:
        - name: temp-data
          mountPath: /app/data
      volumes:
      - name: temp-data
        emptyDir: {}
{{- end }}